name: core_module
description: A new Flutter package project.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.2
  supabase_flutter: ^1.10.25
  hive_flutter: ^1.1.0
  uno: ^1.1.8
  http: ^1.1.0
  logger: ^1.3.0
  intl: ^0.18.1
  connectivity_plus: ^4.0.0
  url_launcher: ^6.1.10
  flutter_svg: ^2.0.5
  email_validator: ^2.1.17
  build_runner: ^2.3.3   # <-- and make sure that is also there
  hive_generator: ^2.0.0 # <-- this line
  flutter_modular: ^6.3.2
  path_provider: ^2.0.14
  upgrader: ^7.0.0
  flutter_lints: ^2.0.1
  design_system:
    path: ../design_system
  lyric_module:
    path: ../lyric_module
  service_module:
    path: ../service_module
  auth_module:
    path: ../auth_module
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  bloc_test: ^9.1.1
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/data/saturday-services/
    - assets/data/sunday-morning-services/
    - assets/data/sunday-evening-services/
    - assets/data/unknown-lyrics/
# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
