name: core_module
description: A new Flutter package project.
version: 0.0.2
publish_to: 'none'
resolution: workspace

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.0.0
  supabase_flutter: ^2.6.0
  hive_flutter: ^1.1.0
  http: ^1.5.0
  logger: ^2.4.0
  intl: ^0.20.2
  connectivity_plus: ^6.0.5
  url_launcher: ^6.1.10
  email_validator: ^3.0.0
  flutter_modular: ^6.3.2
  path_provider: ^2.0.14
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.5
  vector_math: ^2.1.4
  flutter_svg: ^2.0.10+1
  google_maps_flutter: ^2.7.0
  equatable: ^2.0.5
  google_sign_in: ^7.1.1
  image_picker: ^1.1.2
  diacritic: ^0.1.6
  cached_network_image: ^3.4.1
  bloc_concurrency: ^0.3.0
  device_info_plus: ^12.2.0
  uno: ^1.1.12
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  hive_generator: ^2.0.1
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/data/saturday-services/
    - assets/data/sunday-morning-services/
    - assets/data/sunday-evening-services/
    - assets/data/unknown-lyrics/
    - assets/data/events/
    - assets/icons/
    - assets/images/
    - assets/mocks/
    - assets/images/auth/
    - assets/icons/auth/
# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
